Major Refactor
thewh1teagle/amal_appointment pull request #1
Opened 2022-12-20 16:11 UTC by dahanj95

Reorganized the code

2022-12-20 17:37 UTC, thewh1teagle requested changes

2022-12-30 19:23 UTC, dahanj95 commented on src/watchdog.py
> +        self.branch = branch
Yakov, branch in english means "sniff" סניף

2022-12-30 19:24 UTC, dahanj95 commented on .env
> +branch=11
I removed in my commit settings.py and migrated all settings to .env file

2022-12-30 19:24 UTC, dahanj95 commented on src/main.py
> +def onAvailable(cnt, cname):
Naming conventions, I personally name like i'm used to in .net. You can change it to snake case and merge the pull.

2022-12-30 19:25 UTC, dahanj95 commented on src/watchdog.py
> +    def __init__(self, branch, month, onAvailable) -> None:
Yep, if you want i can add support to multiple dates and locations in the future. Do you need it now?

2022-12-30 19:26 UTC, dahanj95 commented on src/watchdog.py
> +        if (available > 0):
Still learning from you everyday :)

2023-01-14 20:28 UTC, dahanj95 commented on src/watchdog.py
> +        self.branch = branch
Do you still want to replace "branch" with a different term? I think branch is suitable, I'll wait for you to decide and reply back.

2023-01-14 20:30 UTC, dahanj95 commented on src/watchdog.py
> +    def __init__(self, branch, month, onAvailable) -> None:
Working on a structural change to add support for multiple months and branches (locations).

2023-01-14 23:03 UTC, thewh1teagle commented on src/watchdog.py
> +        self.branch = branch
Got it. branch is better name ok

2023-01-15 10:53 UTC, dahanj95 commented
Okay Yakov, I've done everything you mentioned ;] I think it's safe to merge the pull request.

2023-04-20 09:05 UTC, closed without merging